# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
      cd bff-ura-midway && npm ci
  displayName: 'Install project dependencies'
- script: |
      cd bff-ura-midway && npm run cypress:verify
  displayName: 'Verify if Cypress can be executed'
- script: |
      cd bff-ura-midway && npm run cypress:run
  displayName: 'Executed test Cypress'
- task: PublishTestResults@2
  displayName: 'Publish the test reports'
  inputs:
    testResultsFiles: '**/test-*.xml'
  condition: succeededOrFailed()
  continueOnError: true